const {test} = require('node:test');
const assert = require('node:assert/strict');
const {initializeApp} = require('firebase-admin/app');
const {getFirestore} = require('firebase-admin/firestore');
const {getStorage} = require('firebase-admin/storage');
if(process.env.FIRESTORE_EMULATOR_HOST!=='127.0.0.1:8185' || process.env.FIREBASE_STORAGE_EMULATOR_HOST!=='127.0.0.1:9198' || process.env.GCLOUD_PROJECT!=='demo-aqar')throw Error('Isolated demo emulators required');
initializeApp({projectId:'demo-aqar',storageBucket:'demo-aqar.appspot.com'});
const db=getFirestore(), f=require('./booking_functions');
const call=(name,uid,data)=>f[name].run({auth:{uid},data});
test('booking lifecycle serializes overlapping approvals, enforces identities and manual receipts',async()=>{
  for(const uid of ['owner','customer1','customer2','admin','reviewer','stranger'])await db.doc(`users/${uid}`).set({name:uid,phone:'07701234567',isAdmin:uid==='admin',isBlocked:false,canReviewBookingPayments:uid==='reviewer'});
  await db.doc('settings/bookings').set({holdMinutes:30,qicard:{enabled:true,account:'test account'}});
  const venue=await call('saveBookingVenue','admin',{ownerId:'owner',name:'test venue',location:'Anbar',category:'farm',price:100000,deposit:25000,terms:'test terms',cancellationPolicy:{freeCancellationHours:24,lateRefundPercent:20},active:true});
  await assert.rejects(call('saveBookingVenue','owner',{ownerId:'owner'}));
  const data={venueId:venue.id,requestId:'request',start:Date.now()+86400000,end:Date.now()+90000000,acceptedTerms:'test terms',price:100000,deposit:25000,cancellationPolicy:{freeCancellationHours:24,lateRefundPercent:20}};
  await assert.rejects(call('requestBooking','customer1',{...data,price:1}));
  const a=await call('requestBooking','customer1',data), b=await call('requestBooking','customer2',data);
  assert.equal((await call('requestBooking','customer1',data)).id,a.id);
  await assert.rejects(call('actOnBooking','stranger',{bookingId:a.id,action:'approve'}));
  const results=await Promise.allSettled([a,b].map(r=>call('actOnBooking','owner',{bookingId:r.id,action:'approve'})));
  assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
  const chosen=results[0].status==='fulfilled'?a:b, uid=chosen===a?'customer1':'customer2';
  const record=(await db.doc(`bookings/${chosen.id}`).get()).data();
  assert.equal(record.total,100000);assert.equal(record.customerName,uid);assert.equal(record.ownerName,'owner');assert.equal(record.venueName,'test venue');assert.equal(record.remaining,100000);
  await assert.rejects(call('actOnBooking','admin',{bookingId:chosen.id,action:'confirmPayment'}));
  const path=`booking_receipts/${chosen.id}/${uid}/123.jpg`;
  await getStorage().bucket().file(path).save(Buffer.from('test receipt'),{resumable:false,metadata:{contentType:'image/jpeg'}});
  await assert.rejects(call('actOnBooking','stranger',{bookingId:chosen.id,action:'submitPayment',receiptPath:path,method:'qicard',transactionNumber:'t1'}));
  await call('actOnBooking',uid,{bookingId:chosen.id,action:'submitPayment',receiptPath:path,method:'qicard',transactionNumber:'t1'});
  await assert.rejects(call('actOnBooking','owner',{bookingId:chosen.id,action:'confirmPayment'}));
  await assert.rejects(call('actOnBooking','admin',{bookingId:chosen.id,action:'confirmPayment'}));
  await call('actOnBooking','reviewer',{bookingId:chosen.id,action:'confirmPayment'});
  const paid=(await db.doc(`bookings/${chosen.id}`).get()).data();assert.equal(paid.paid,25000);assert.equal(paid.remaining,75000);

  await assert.rejects(call('reportBooking','stranger',{bookingId:chosen.id,reason:'spam'}));
  await call('reportBooking',uid,{bookingId:chosen.id,reason:'report'});
  assert.equal((await db.doc(`booking_reports/${chosen.id}_${uid}`).get()).data().status,'open');
  const snap=await db.doc(`bookings/${chosen.id}`).get();
  const event={data:{after:snap,before:{data:()=>({status:'payment_review'})}},params:{bookingId:chosen.id}};
  await Promise.all([f.bookingNotifications.run(event),f.bookingNotifications.run(event)]);
  const notices=await db.collection('notifications').where('bookingId','==',chosen.id).get();assert.equal(notices.size,4);
  await call('actOnBooking',uid,{bookingId:chosen.id,action:'cancel',reason:'cancel'});
  const cancelled=(await db.doc(`bookings/${chosen.id}`).get()).data();
  assert.equal(cancelled.refundDue,5000);
  await assert.rejects(call('actOnBooking','admin',{bookingId:chosen.id,action:'settleRefund',refundReference:'r1'}));
  await call('actOnBooking','reviewer',{bookingId:chosen.id,action:'settleRefund',refundReference:'r1'});
  await assert.rejects(call('actOnBooking','reviewer',{bookingId:chosen.id,action:'settleRefund',refundReference:'r1'}));
  assert.equal((await db.doc(`bookings/${chosen.id}`).get()).data().refunded,5000);
  const next={...data,requestId:'adjacent',start:data.end,end:data.end+3600000};
  const adjacent=await call('requestBooking','customer1',next);
  await call('actOnBooking','owner',{bookingId:adjacent.id,action:'approve'});
  await db.doc(`bookings/${adjacent.id}`).update({holdUntil:Date.now()-1});
  const replacement=await call('requestBooking','customer2',{...next,requestId:'expired-replacement'});
  await call('actOnBooking','owner',{bookingId:replacement.id,action:'approve'});
  await f.expireBookingHolds.run({});
  assert.equal((await db.doc(`bookings/${adjacent.id}`).get()).data().status,'expired');
  assert.equal((await db.doc(`bookings/${replacement.id}`).get()).data().status,'held');
  await assert.rejects(call('actOnBooking','customer1',{bookingId:adjacent.id,action:'submitPayment',receiptPath:path,method:'qicard',transactionNumber:'late'}));
  await db.doc('users/customer2').update({isBlocked:true});
  await assert.rejects(call('requestBooking','customer2',{...next,requestId:'blocked'}));
});

test('phase two pricing, independent review, cancellation during receipt review and refund audit',async()=>{
  for(const uid of ['p2owner','p2customer','p2reviewer','p2admin']) await db.doc(`users/${uid}`).set({name:uid,phone:'07700000000',isAdmin:uid==='p2admin',canReviewBookingPayments:uid==='p2reviewer',isBlocked:false});
  const cp={freeCancellationHours:48,lateRefundPercent:25};
  const shifts=[{id:'night',name:'night',checkInMinute:1200,checkOutMinute:480,price:200000}];
  const v=await call('saveBookingVenue','p2admin',{ownerId:'p2owner',name:'night farm',location:'Baghdad',category:'farm',price:100000,deposit:20000,terms:'terms',active:true,pricingMode:'shifts',shifts,cancellationPolicy:cp});
  const date=new Date(Date.now()+86400000*5);date.setUTCHours(17,0,0,0);
  const data={venueId:v.id,requestId:'night',start:date.getTime(),end:date.getTime()+12*3600000,shiftId:'night',price:200000,deposit:20000,acceptedTerms:'terms',cancellationPolicy:cp};
  await assert.rejects(call('requestBooking','p2customer',{...data,price:100000}));
  await assert.rejects(call('requestBooking','p2customer',{...data,start:data.start+60000,end:data.end+60000}));
  await assert.rejects(call('requestBooking','p2customer',{...data,cancellationPolicy:{...cp,lateRefundPercent:100}}));
  const booking=await call('requestBooking','p2customer',data);
  assert.equal((await db.doc(`bookings/${booking.id}`).get()).data().pricing.name,'night');
  await assert.rejects(call('setBookingPaymentReviewer','p2customer',{userId:'p2customer',enabled:true}));
  await call('setBookingPaymentReviewer','p2admin',{userId:'p2owner',enabled:true});
  await call('actOnBooking','p2owner',{bookingId:booking.id,action:'approve'});
  const path=`booking_receipts/${booking.id}/p2customer/222.jpg`;
  await getStorage().bucket().file(path).save(Buffer.from('receipt'),{resumable:false,metadata:{contentType:'image/jpeg'}});
  await assert.rejects(call('actOnBooking','p2customer',{bookingId:booking.id,action:'submitPayment',receiptPath:path,method:'zaincash',transactionNumber:'z'}));
  await call('actOnBooking','p2customer',{bookingId:booking.id,action:'submitPayment',receiptPath:path,method:'qicard',transactionNumber:'q'});
  assert.match((await db.doc(`bookings/${booking.id}`).get()).data().paymentAccount,/7066135323/);
  await call('actOnBooking','p2owner',{bookingId:booking.id,action:'cancel',reason:'owner cancellation'});
  assert.equal((await db.doc(`bookings/${booking.id}`).get()).data().status,'cancel_requested');
  await assert.rejects(call('requestBooking','p2reviewer',{...data,requestId:'blocked-slot'}));
  await assert.rejects(call('actOnBooking','p2owner',{bookingId:booking.id,action:'confirmPayment'}));
  await assert.rejects(call('actOnBooking','p2admin',{bookingId:booking.id,action:'confirmPayment'}));
  await call('actOnBooking','p2reviewer',{bookingId:booking.id,action:'confirmPayment'});
  const cancelled=(await db.doc(`bookings/${booking.id}`).get()).data();
  assert.equal(cancelled.status,'cancelled');assert.equal(cancelled.refundDue,20000);assert.equal(cancelled.remaining,0);assert.equal(cancelled.contractRemaining,180000);
  await call('actOnBooking','p2reviewer',{bookingId:booking.id,action:'settleRefund',refundReference:'refund-222'});
  const after=await db.doc(`bookings/${booking.id}`).get();
  assert.equal(after.data().refundReference,'refund-222');assert.equal(after.data().refundSettledBy,'p2reviewer');
  await Promise.all([1,2].map(()=>f.bookingNotifications.run({data:{after,before:{data:()=>cancelled}},params:{bookingId:booking.id}})));
  const notices=await db.collection('notifications').where('bookingId','==',booking.id).get();
  assert.equal(notices.docs.filter(n=>n.data().userId==='p2owner').length,1);
  assert.equal(notices.docs.filter(n=>n.data().userId==='p2admin').length,1);
  await call('saveBookingVenue','p2admin',{id:v.id,ownerId:'p2owner',name:'night farm',location:'Baghdad',category:'farm',price:100000,deposit:20000,terms:'changed',active:true,pricingMode:'hourly',hourlyPrice:30000,cancellationPolicy:{freeCancellationHours:2,lateRefundPercent:0}});
  const old=(await db.doc(`bookings/${booking.id}`).get()).data();assert.equal(old.terms,'terms');assert.equal(old.cancellationPolicy.freeCancellationHours,48);
  const hourly={...data,requestId:'hourly',start:data.end,end:data.end+2*3600000,price:60000,acceptedTerms:'changed',cancellationPolicy:{freeCancellationHours:2,lateRefundPercent:0}};
  const h=await call('requestBooking','p2customer',hourly);assert.equal((await db.doc(`bookings/${h.id}`).get()).data().pricing.hours,2);
  await assert.rejects(call('requestBooking','p2customer',{...hourly,requestId:'fraction',end:hourly.start+90*60000,price:45000}));
  await db.doc('users/p2reviewer').update({isBlocked:true});
  await assert.rejects(call('actOnBooking','p2reviewer',{bookingId:h.id,action:'confirmPayment'}));
});
