const {test} = require('node:test');
const assert = require('node:assert/strict');
const {initializeApp} = require('firebase-admin/app');
const {getFirestore} = require('firebase-admin/firestore');
const {getStorage} = require('firebase-admin/storage');
if(process.env.FIRESTORE_EMULATOR_HOST!=='127.0.0.1:8185' || process.env.FIREBASE_STORAGE_EMULATOR_HOST!=='127.0.0.1:9198' || process.env.GCLOUD_PROJECT!=='demo-aqar')throw Error('Isolated demo emulators required');
initializeApp({projectId:'demo-aqar',storageBucket:'demo-aqar.appspot.com'});
const db=getFirestore(), f=require('./booking_functions');
const call=(name,uid,data)=>f[name].run({auth:{uid},data});
test('owner management, closures, private availability, transfer, QR and completed reviews',async()=>{
  for(const uid of ['xadmin','xowner','xnew','xcustomer','xother']) await db.doc(`users/${uid}`).set({name:uid,phone:'07700000000',isAdmin:uid==='xadmin',isBlocked:false});
  const payload={ownerId:'xowner',name:'test',location:'Anbar',category:'chalet',price:100000,deposit:20000,terms:'terms',active:true,cancellationPolicy:{freeCancellationHours:24,lateRefundPercent:20}};
  const venue=await call('saveBookingVenue','xadmin',payload);
  await assert.rejects(call('saveBookingVenue','xother',{...payload,id:venue.id}));
  await call('saveBookingVenue','xowner',{...payload,id:venue.id,price:120000});
  await assert.rejects(call('saveBookingVenue','xowner',{...payload,id:venue.id,active:false}));
  const start=Date.now()+86400000,end=start+3600000;
  await assert.rejects(call('saveBookingClosure','xother',{venueId:venue.id,requestId:'x',start,end,reason:'outside'}));
  await call('saveBookingClosure','xowner',{venueId:venue.id,requestId:'x',start,end,reason:'external booking'});
  await call('getBookingAvailability','xcustomer',{venueId:venue.id,start:Date.now()-60000,end:Date.now()+60000});
  const a=await call('getBookingAvailability','xcustomer',{venueId:venue.id,start:start-1000,end:end+1000});
  assert.deepEqual(Object.keys(a.slots[0]).sort(),['end','shiftId','start','state']);
  assert.equal(a.slots[0].state,'unavailable');
  await assert.rejects(call('requestBooking','xcustomer',{venueId:venue.id,requestId:'closed',start,end,price:120000,deposit:20000,acceptedTerms:'terms',cancellationPolicy:payload.cancellationPolicy}));
  await assert.rejects(call('reopenBookingClosure','xother',{closureId:`${venue.id}_x`}));
  await call('reopenBookingClosure','xowner',{closureId:`${venue.id}_x`});
  assert.equal((await call('getBookingAvailability','xcustomer',{venueId:venue.id,start:start-1000,end:end+1000})).slots.length,0);
  const transfer=await call('requestBookingOwnershipTransfer','xowner',{venueId:venue.id,newOwnerId:'xnew',requestId:'transfer',reason:'approved sale'});
  await assert.rejects(call('actOnBookingOwnershipTransfer','xadmin',{transferId:transfer.id,action:'approve'}));
  await call('actOnBookingOwnershipTransfer','xnew',{transferId:transfer.id,action:'accept'});
  await call('actOnBookingOwnershipTransfer','xadmin',{transferId:transfer.id,action:'approve'});
  assert.equal((await db.doc(`booking_venues/${venue.id}`).get()).data().ownerId,'xnew');
  await assert.rejects(call('saveBookingVenue','xowner',{...payload,id:venue.id}));
  const bookingRef=db.doc('bookings/xqr');
  await bookingRef.set({venueId:venue.id,ownerId:'xnew',customerId:'xcustomer',status:'confirmed',version:1,start:Date.now()-1000,end:Date.now()+60000});
  await assert.rejects(call('issueBookingCheckInCode','xother',{bookingId:'xqr'}));
  const code=await call('issueBookingCheckInCode','xcustomer',{bookingId:'xqr'});
  await assert.rejects(call('verifyBookingCheckInCode','xother',{code:code.code}));
  await call('verifyBookingCheckInCode','xnew',{code:code.code});
  await assert.rejects(call('verifyBookingCheckInCode','xnew',{code:code.code}));
  await assert.rejects(call('reviewCompletedBooking','xcustomer',{bookingId:'xqr',rating:5,comment:'great'}));
  await bookingRef.update({end:Date.now()-1});
  await call('actOnBooking','xnew',{bookingId:'xqr',action:'complete'});
  await call('reviewCompletedBooking','xcustomer',{bookingId:'xqr',rating:5,comment:'great'});
  await assert.rejects(call('reviewCompletedBooking','xcustomer',{bookingId:'xqr',rating:5,comment:'duplicate'}));
  await bookingRef.update({paid:20000,commissionBps:500});
  await db.doc('users/xreviewer').set({name:'reviewer',phone:'07700000000',isBlocked:false,canReviewBookingPayments:true});
  await call('setBookingVenueStaff','xnew',{venueId:venue.id,userId:'xreviewer',scopes:['bookings']});
  await assert.rejects(call('actOnBooking','xreviewer',{bookingId:'xqr',action:'settleOwner',settlementReference:'r'}));
  const staffRequests=await call('getBookingStaffRequests','xreviewer',{venueId:venue.id});
  assert.equal('paid' in staffRequests.bookings[0],false);
  await call('setBookingVenueStaff','xnew',{venueId:venue.id,userId:'xreviewer',scopes:[]});
  await assert.rejects(call('getBookingStaffRequests','xreviewer',{venueId:venue.id}));
  await assert.rejects(call('sendBookingMessage','xother',{bookingId:'xqr',requestId:'one',message:'hello'}));
  await call('sendBookingMessage','xcustomer',{bookingId:'xqr',requestId:'one',message:'hello'});
  await call('sendBookingMessage','xcustomer',{bookingId:'xqr',requestId:'one',message:'hello'});
  await assert.rejects(call('sendBookingMessage','xcustomer',{bookingId:'xqr',requestId:'two',message:'too soon'}));
  await assert.rejects(call('actOnBooking','xnew',{bookingId:'xqr',action:'settleOwner',settlementReference:'r'}));
  await call('actOnBooking','xreviewer',{bookingId:'xqr',action:'settleOwner',settlementReference:'r'});
  const settled=(await bookingRef.get()).data();
  assert.equal(settled.ownerSettled,19000);assert.equal(settled.platformCommission,1000);
  await assert.rejects(call('actOnBooking','xreviewer',{bookingId:'xqr',action:'settleOwner',settlementReference:'r'}));
  const draft=await call('saveBookingVenue','xowner',{...payload,active:false});
  await assert.rejects(call('saveBookingVenue','xadmin',{...payload,id:draft.id,active:true}));
  const proofPath=`booking_ownership_documents/${draft.id}/xowner/proof.jpg`;
  await getStorage().bucket().file(proofPath).save(Buffer.from('fixture'),{resumable:false,metadata:{contentType:'image/jpeg'}});
  await call('submitBookingOwnershipProof','xowner',{venueId:draft.id,path:proofPath});
  await assert.rejects(call('reviewBookingOwnershipProof','xowner',{venueId:draft.id,approved:true,reason:'self'}));
  await call('reviewBookingOwnershipProof','xadmin',{venueId:draft.id,approved:true,reason:'fixture checked'});
  await call('saveBookingVenue','xadmin',{...payload,id:draft.id,active:true});
  const mediaPath=`booking_media/${draft.id}/xowner/photo.jpg`;
  await getStorage().bucket().file(mediaPath).save(Buffer.from('fixture'),{resumable:false,metadata:{contentType:'image/jpeg'}});
  await call('submitBookingMedia','xowner',{venueId:draft.id,path:mediaPath});
  await assert.rejects(call('reviewBookingMedia','xother',{mediaId:`${draft.id}_photo.jpg`,approved:true}));
  await call('reviewBookingMedia','xadmin',{mediaId:`${draft.id}_photo.jpg`,approved:true});
  assert.deepEqual((await db.doc(`booking_venues/${draft.id}`).get()).data().mediaPaths,[mediaPath]);
  await assert.rejects(call('saveBookingOffer','xother',{venueId:draft.id,percent:25,until:Date.now()+60000}));
  await call('saveBookingOffer','xowner',{venueId:draft.id,percent:25,until:Date.now()+60000});
  assert.equal((await db.doc(`booking_venues/${draft.id}`).get()).data().offer.percent,25);
  await call('setBookingVenueStaff','xowner',{venueId:draft.id,userId:'xother',scopes:['calendar']});
  await db.doc('users/xowner').update({isBlocked:true});
  await assert.rejects(call('saveBookingClosure','xother',{venueId:draft.id,requestId:'blocked-principal',start,end,reason:'must fail'}));
  await db.doc('users/xadmin').update({isBlocked:true});
  await db.doc('users/xreviewer').update({canReviewBookingPayments:false});
  await assert.rejects(call('saveBookingVenue','xadmin',payload));
});
test('booking lifecycle serializes overlapping approvals, enforces identities and manual receipts',async()=>{
  for(const uid of ['owner','customer1','customer2','admin','reviewer','stranger'])await db.doc(`users/${uid}`).set({name:uid,phone:'07701234567',isAdmin:uid==='admin',isBlocked:false,canReviewBookingPayments:uid==='reviewer'});
  await db.doc('payment_configuration/shared').set({revision:1,methods:{qicard:{enabled:true,number:'7066135323'},zaincash:{enabled:false,number:''}}});
  await db.doc('settings/bookings').set({holdMinutes:30,qicard:{enabled:true,account:'test account'}});
  const venue=await call('saveBookingVenue','admin',{ownerId:'owner',name:'test venue',location:'Anbar',category:'farm',price:100000,deposit:25000,terms:'test terms',cancellationPolicy:{freeCancellationHours:24,lateRefundPercent:20},active:true});
  await assert.rejects(call('saveBookingVenue','owner',{ownerId:'owner'}));
  const data={venueId:venue.id,requestId:'request',start:Date.now()+86400000,end:Date.now()+90000000,acceptedTerms:'test terms',price:100000,deposit:25000,cancellationPolicy:{freeCancellationHours:24,lateRefundPercent:20}};
  await assert.rejects(call('requestBooking','customer1',{...data,price:1}));
  const a=await call('requestBooking','customer1',data), b=await call('requestBooking','customer2',data);
  assert.equal((await call('requestBooking','customer1',data)).id,a.id);
  await assert.rejects(call('actOnBooking','stranger',{bookingId:a.id,action:'approve'}));
  const results=await Promise.allSettled([a,b].map(r=>call('actOnBooking','owner',{bookingId:r.id,action:'approve'})));
  assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
  const chosen=results[0].status==='fulfilled'?a:b, uid=chosen===a?'customer1':'customer2';
  const record=(await db.doc(`bookings/${chosen.id}`).get()).data();
  assert.equal(record.total,100000);assert.equal(record.customerName,uid);assert.equal(record.ownerName,'owner');assert.equal(record.venueName,'test venue');assert.equal(record.remaining,100000);
  await assert.rejects(call('actOnBooking','admin',{bookingId:chosen.id,action:'confirmPayment'}));
  const path=`booking_receipts/${chosen.id}/${uid}/123.jpg`;
  await getStorage().bucket().file(path).save(Buffer.from('test receipt'),{resumable:false,metadata:{contentType:'image/jpeg'}});
  await assert.rejects(call('actOnBooking','stranger',{bookingId:chosen.id,action:'submitPayment',receiptPath:path,method:'qicard',expectedNumber:'7066135323',transactionNumber:'t1'}));
  await db.doc('payment_configuration/shared').update({'methods.qicard.enabled':false});
  await assert.rejects(call('actOnBooking',uid,{bookingId:chosen.id,action:'submitPayment',receiptPath:path,method:'qicard',expectedNumber:'7066135323',transactionNumber:'t1'}));
  await db.doc('payment_configuration/shared').update({'methods.qicard.enabled':true});
  await call('actOnBooking',uid,{bookingId:chosen.id,action:'submitPayment',receiptPath:path,method:'qicard',expectedNumber:'7066135323',transactionNumber:'t1'});
  assert.equal((await db.doc(`bookings/${chosen.id}`).get()).data().paymentAccountSnapshot.number,'7066135323');
  await db.doc('payment_configuration/shared').update({'methods.qicard.enabled':false});

  await assert.rejects(call('actOnBooking','owner',{bookingId:chosen.id,action:'confirmPayment'}));
  await assert.rejects(call('actOnBooking','admin',{bookingId:chosen.id,action:'confirmPayment'}));
  const concurrentReviews=await Promise.allSettled([1,2].map(()=>call('actOnBooking','reviewer',{bookingId:chosen.id,action:'confirmPayment'})));
  assert.equal(concurrentReviews.filter(r=>r.status==='fulfilled').length,1);
  const paid=(await db.doc(`bookings/${chosen.id}`).get()).data();assert.equal(paid.paid,25000);assert.equal(paid.remaining,75000);

  await assert.rejects(call('reportBooking','stranger',{bookingId:chosen.id,reason:'spam'}));
  await call('reportBooking',uid,{bookingId:chosen.id,reason:'report'});
  assert.equal((await db.doc(`booking_reports/${chosen.id}_${uid}`).get()).data().status,'open');
  const snap=await db.doc(`bookings/${chosen.id}`).get();
  const event={data:{after:snap,before:{data:()=>({status:'payment_review'})}},params:{bookingId:chosen.id}};
  await Promise.all([f.bookingNotifications.run(event),f.bookingNotifications.run(event)]);
  const notices=await db.collection('notifications').where('bookingId','==',chosen.id).get();assert.equal(notices.size,4);
  await call('actOnBooking',uid,{bookingId:chosen.id,action:'cancel',reason:'cancel'});
  const cancelled=(await db.doc(`bookings/${chosen.id}`).get()).data();
  assert.equal(cancelled.refundDue,5000);
  await assert.rejects(call('actOnBooking','admin',{bookingId:chosen.id,action:'settleRefund',refundReference:'r1'}));
  const concurrentRefunds=await Promise.allSettled([1,2].map(()=>call('actOnBooking','reviewer',{bookingId:chosen.id,action:'settleRefund',refundReference:'r1'})));
  assert.equal(concurrentRefunds.filter(r=>r.status==='fulfilled').length,1);
  await assert.rejects(call('actOnBooking','reviewer',{bookingId:chosen.id,action:'settleRefund',refundReference:'r1'}));
  assert.equal((await db.doc(`bookings/${chosen.id}`).get()).data().refunded,5000);
  const next={...data,requestId:'adjacent',start:data.end,end:data.end+3600000};
  const adjacent=await call('requestBooking','customer1',next);
  await call('actOnBooking','owner',{bookingId:adjacent.id,action:'approve'});
  await db.doc(`bookings/${adjacent.id}`).update({holdUntil:Date.now()-1});
  const replacement=await call('requestBooking','customer2',{...next,requestId:'expired-replacement'});
  await call('actOnBooking','owner',{bookingId:replacement.id,action:'approve'});
  await f.expireBookingHolds.run({});
  assert.equal((await db.doc(`bookings/${adjacent.id}`).get()).data().status,'expired');
  assert.equal((await db.doc(`bookings/${replacement.id}`).get()).data().status,'held');
  await assert.rejects(call('actOnBooking','customer1',{bookingId:adjacent.id,action:'submitPayment',receiptPath:path,method:'qicard',expectedNumber:'7066135323',transactionNumber:'late'}));
  await db.doc('users/customer2').update({isBlocked:true});
  await assert.rejects(call('requestBooking','customer2',{...next,requestId:'blocked'}));
});

test('phase two pricing, independent review, cancellation during receipt review and refund audit',async()=>{
  await db.doc('payment_configuration/shared').update({'methods.qicard.enabled':true});
  for(const uid of ['p2owner','p2customer','p2reviewer','p2admin']) await db.doc(`users/${uid}`).set({name:uid,phone:'07700000000',isAdmin:uid==='p2admin',canReviewBookingPayments:uid==='p2reviewer',isBlocked:false});
  const cp={freeCancellationHours:48,lateRefundPercent:25};
  const shifts=[{id:'night',name:'night',checkInMinute:1200,checkOutMinute:480,price:200000}];
  const v=await call('saveBookingVenue','p2admin',{ownerId:'p2owner',name:'night farm',location:'Baghdad',category:'farm',price:100000,deposit:20000,terms:'terms',active:true,pricingMode:'shifts',shifts,cancellationPolicy:cp});
  const date=new Date(Date.now()+86400000*5);date.setUTCHours(17,0,0,0);
  const data={venueId:v.id,requestId:'night',start:date.getTime(),end:date.getTime()+12*3600000,shiftId:'night',price:200000,deposit:20000,acceptedTerms:'terms',cancellationPolicy:cp};
  await assert.rejects(call('requestBooking','p2customer',{...data,price:100000}));
  await assert.rejects(call('requestBooking','p2customer',{...data,start:data.start+60000,end:data.end+60000}));
  await assert.rejects(call('requestBooking','p2customer',{...data,cancellationPolicy:{...cp,lateRefundPercent:100}}));
  const booking=await call('requestBooking','p2customer',data);
  assert.equal((await db.doc(`bookings/${booking.id}`).get()).data().pricing.name,'night');
  await assert.rejects(call('setBookingPaymentReviewer','p2customer',{userId:'p2customer',enabled:true}));
  await call('setBookingPaymentReviewer','p2admin',{userId:'p2owner',enabled:true});
  await assert.rejects(call('setBookingPaymentReviewer','p2admin',{userId:'p2admin',enabled:true}));
  assert.equal((await db.collection('booking_finance_audit').where('targetUid','==','p2owner').get()).size,1);
  await call('actOnBooking','p2owner',{bookingId:booking.id,action:'approve'});
  const path=`booking_receipts/${booking.id}/p2customer/222.jpg`;
  await getStorage().bucket().file(path).save(Buffer.from('receipt'),{resumable:false,metadata:{contentType:'image/jpeg'}});
  await assert.rejects(call('actOnBooking','p2customer',{bookingId:booking.id,action:'submitPayment',receiptPath:path,method:'zaincash',transactionNumber:'z'}));
  await call('actOnBooking','p2customer',{bookingId:booking.id,action:'submitPayment',receiptPath:path,method:'qicard',expectedNumber:'7066135323',transactionNumber:'q'});
  assert.match((await db.doc(`bookings/${booking.id}`).get()).data().paymentAccount,/7066135323/);
  await call('actOnBooking','p2owner',{bookingId:booking.id,action:'cancel',reason:'owner cancellation'});
  assert.equal((await db.doc(`bookings/${booking.id}`).get()).data().status,'cancel_requested');
  await assert.rejects(call('requestBooking','p2reviewer',{...data,requestId:'blocked-slot'}));
  await assert.rejects(call('actOnBooking','p2owner',{bookingId:booking.id,action:'confirmPayment'}));
  await assert.rejects(call('actOnBooking','p2admin',{bookingId:booking.id,action:'confirmPayment'}));
  await call('actOnBooking','p2reviewer',{bookingId:booking.id,action:'confirmPayment'});
  const cancelled=(await db.doc(`bookings/${booking.id}`).get()).data();
  assert.equal(cancelled.status,'cancelled');assert.equal(cancelled.refundDue,20000);assert.equal(cancelled.remaining,0);assert.equal(cancelled.contractRemaining,180000);
  await call('actOnBooking','p2reviewer',{bookingId:booking.id,action:'settleRefund',refundReference:'refund-222'});
  const after=await db.doc(`bookings/${booking.id}`).get();
  assert.equal(after.data().refundReference,'refund-222');assert.equal(after.data().refundSettledBy,'p2reviewer');
  const audit = await db.collection('booking_action_audit').where('bookingId','==',booking.id).get();
  assert.equal(audit.size,6);
  assert.equal(audit.docs.filter(s=>s.data().action==='settleRefund')[0].data().actorUid,'p2reviewer');
  await Promise.all([1,2].map(()=>f.bookingNotifications.run({data:{after,before:{data:()=>cancelled}},params:{bookingId:booking.id}})));
  const notices=await db.collection('notifications').where('bookingId','==',booking.id).get();
  assert.equal(notices.docs.filter(n=>n.data().userId==='p2owner').length,1);
  assert.equal(notices.docs.filter(n=>n.data().userId==='p2admin').length,1);
  await call('saveBookingVenue','p2admin',{id:v.id,ownerId:'p2owner',name:'night farm',location:'Baghdad',category:'farm',price:100000,deposit:20000,terms:'changed',active:true,pricingMode:'hourly',hourlyPrice:30000,cancellationPolicy:{freeCancellationHours:2,lateRefundPercent:0}});
  const old=(await db.doc(`bookings/${booking.id}`).get()).data();assert.equal(old.terms,'terms');assert.equal(old.cancellationPolicy.freeCancellationHours,48);
  const hourly={...data,requestId:'hourly',start:data.end,end:data.end+2*3600000,price:60000,acceptedTerms:'changed',cancellationPolicy:{freeCancellationHours:2,lateRefundPercent:0}};
  const h=await call('requestBooking','p2customer',hourly);assert.equal((await db.doc(`bookings/${h.id}`).get()).data().pricing.hours,2);
  await assert.rejects(call('requestBooking','p2customer',{...hourly,requestId:'fraction',end:hourly.start+90*60000,price:45000}));
  await db.doc('users/p2reviewer').update({isBlocked:true});
  await assert.rejects(call('actOnBooking','p2reviewer',{bookingId:h.id,action:'confirmPayment'}));
});

test('discovery metadata, independent review projection and support authorization',async()=>{
  for(const uid of ['sadmin','sowner','scustomer','sother']) await db.doc(`users/${uid}`).set({name:uid,phone:'07700000000',isAdmin:uid==='sadmin',isBlocked:false});
  const payload={ownerId:'sowner',name:'unit',location:'Anbar',category:'chalet',price:100000,deposit:20000,terms:'terms',active:true,cancellationPolicy:{freeCancellationHours:24,lateRefundPercent:20},capacity:8,bedrooms:2,amenities:['pool'],complexName:'resort',unitName:'A'};
  const v=await call('saveBookingVenue','sadmin',payload);
  await assert.rejects(call('saveBookingVenue','sowner',{...payload,id:v.id,capacity:-1}));
  await assert.rejects(call('saveBookingVenue','sowner',{...payload,id:v.id,amenities:['unknown']}));
  await call('saveBookingVenue','sowner',{...payload,id:v.id,name:'updated'});
  assert.equal((await db.doc(`booking_venues/${v.id}`).get()).data().capacity,8);
  await db.doc('bookings/support-complete').set({venueId:v.id,customerId:'scustomer',ownerId:'sowner',status:'completed'});
  await call('reviewCompletedBooking','scustomer',{bookingId:'support-complete',rating:4,comment:'verified review'});
  assert.equal((await call('getPublishedBookingReviews','sother',{venueId:v.id})).count,0);
  await assert.rejects(call('moderateBookingReview','sowner',{reviewId:'support-complete',approved:true}));
  await call('moderateBookingReview','sadmin',{reviewId:'support-complete',approved:true});
  const reviews=await call('getPublishedBookingReviews','sother',{venueId:v.id});
  assert.equal(reviews.average,4);assert.deepEqual(Object.keys(reviews.reviews[0]).sort(),['comment','rating','verified']);
  await call('moderateBookingReview','sadmin',{reviewId:'support-complete',approved:false});
  assert.equal((await call('getPublishedBookingReviews','sother',{venueId:v.id})).count,0);
  await assert.rejects(call('openBookingSupportTicket','sother',{bookingId:'support-complete',requestId:'ticket',subject:'problem',message:'help'}));
  const ticket=await call('openBookingSupportTicket','scustomer',{bookingId:'support-complete',requestId:'ticket',subject:'problem',message:'help'});
  const retry=await call('openBookingSupportTicket','scustomer',{bookingId:'support-complete',requestId:'ticket',subject:'problem',message:'help'});assert.equal(retry.id,ticket.id);
  await assert.rejects(call('updateBookingSupportTicket','sowner',{ticketId:ticket.id,status:'resolved',response:'answer'}));
  await call('updateBookingSupportTicket','sadmin',{ticketId:ticket.id,status:'in_progress',response:'following up'});
  await call('updateBookingSupportTicket','sadmin',{ticketId:ticket.id,status:'resolved',response:'fixed'});
  assert.equal((await db.doc(`booking_support/${ticket.id}`).get()).data().assignedTo,'sadmin');
  await db.doc('users/scustomer').update({isBlocked:true});
  await assert.rejects(call('openBookingSupportTicket','scustomer',{bookingId:'support-complete',requestId:'blocked',subject:'problem',message:'help'}));
});

test('availability projection, staff QR and retry-safe reminders',async()=>{
  for(const uid of ['tadmin','towner','tstaff','tcustomer']) await db.doc(`users/${uid}`).set({name:uid,phone:'07700000000',isAdmin:uid==='tadmin',isBlocked:false});
  const payload={ownerId:'towner',name:'test',location:'Anbar',category:'chalet',price:100000,deposit:20000,terms:'terms',active:true,cancellationPolicy:{freeCancellationHours:24,lateRefundPercent:20}};
  const v=await call('saveBookingVenue','tadmin',payload),start=Date.now()+3600000,end=start+3600000;
  assert.deepEqual((await call('findAvailableBookingVenues','tcustomer',{venueIds:[v.id],start,end})).venueIds,[v.id]);
  await call('saveBookingClosure','towner',{venueId:v.id,requestId:'closed',start,end,reason:'external'});
  assert.deepEqual((await call('findAvailableBookingVenues','tcustomer',{venueIds:[v.id],start,end})).venueIds,[]);
  await assert.rejects(call('findAvailableBookingVenues','tcustomer',{venueIds:Array(51).fill(v.id),start,end}));
  await call('reopenBookingClosure','towner',{closureId:`${v.id}_closed`});
  await db.doc('bookings/tqr').set({venueId:v.id,ownerId:'towner',customerId:'tcustomer',status:'confirmed',version:1,start:Date.now()-1000,end:Date.now()+60000});
  await call('setBookingVenueStaff','towner',{venueId:v.id,userId:'tstaff',scopes:['checkin']});
  const code=await call('issueBookingCheckInCode','tcustomer',{bookingId:'tqr'});
  await assert.rejects(call('verifyBookingCheckInCode','tstaff',{code:code.code,bookingId:'another'}));
  await call('verifyBookingCheckInCode','tstaff',{code:code.code,bookingId:'tqr'});
  await assert.rejects(call('verifyBookingCheckInCode','tstaff',{code:code.code}));
  const reminder=db.doc('bookings/treminder');
  await reminder.set({venueId:v.id,ownerId:'towner',customerId:'tcustomer',status:'confirmed',start,end});
  await f.remindBookingCustomers.run({});await f.remindBookingCustomers.run({});
  const notes=await db.collection('notifications').where('bookingId','==','treminder').get();
  assert.equal(notes.size,1);
  await db.doc('users/tcustomer').update({isBlocked:true});
  await reminder.update({start:start+1000});await f.remindBookingCustomers.run({});
  assert.equal((await db.collection('notifications').where('bookingId','==','treminder').get()).size,1);
});

test('media removal revokes publication and deletes downloadable object with safe retries',async()=>{
  for(const uid of ['madmin','mowner','mother']) await db.doc(`users/${uid}`).set({name:uid,phone:'07700000000',isAdmin:uid==='madmin',isBlocked:false});
  const payload={ownerId:'mowner',name:'media',location:'Anbar',category:'chalet',price:100000,deposit:20000,terms:'terms',active:true,cancellationPolicy:{freeCancellationHours:24,lateRefundPercent:20}};
  const v=await call('saveBookingVenue','madmin',payload),path=`booking_media/${v.id}/mowner/photo.jpg`;
  await getStorage().bucket().file(path).save(Buffer.from('synthetic'),{resumable:false,metadata:{contentType:'image/jpeg'}});
  await call('submitBookingMedia','mowner',{venueId:v.id,path});
  await call('reviewBookingMedia','madmin',{mediaId:`${v.id}_photo.jpg`,approved:true});
  await assert.rejects(call('removeBookingMedia','mother',{venueId:v.id,path}));
  await call('removeBookingMedia','mowner',{venueId:v.id,path});
  assert.equal((await db.doc(`booking_legacy_media_deletions/${v.id}_photo.jpg`).get()).data().status,'pending');
  await require('./booking_external_media').cleanupBookingExternalMedia.run({});
  assert.equal((await getStorage().bucket().file(path).exists())[0],false);
  assert.deepEqual((await db.doc(`booking_venues/${v.id}`).get()).data().mediaPaths,[]);
  assert.equal((await db.doc(`booking_media_reviews/${v.id}_photo.jpg`).get()).data().status,'removed');
  await call('removeBookingMedia','mowner',{venueId:v.id,path});
  await assert.rejects(call('reviewBookingMedia','madmin',{mediaId:`${v.id}_photo.jpg`,approved:true}));
});
