const {test} = require('node:test');
const assert = require('node:assert/strict');
const {initializeApp} = require('firebase-admin/app');
const {getFirestore} = require('firebase-admin/firestore');
const {getStorage} = require('firebase-admin/storage');
if(process.env.FIRESTORE_EMULATOR_HOST!=='127.0.0.1:8185' || process.env.FIREBASE_STORAGE_EMULATOR_HOST!=='127.0.0.1:9198' || process.env.GCLOUD_PROJECT!=='demo-aqar')throw Error('Isolated demo emulators required');
initializeApp({projectId:'demo-aqar',storageBucket:'demo-aqar.appspot.com'});
const db=getFirestore(), f=require('./booking_functions');
const call=(name,uid,data)=>f[name].run({auth:{uid},data});
test('booking lifecycle serializes overlapping approvals, enforces identities and manual receipts',async()=>{
  for(const uid of ['owner','customer1','customer2','admin','stranger'])await db.doc(`users/${uid}`).set({name:uid,phone:'07701234567',isAdmin:uid==='admin',isBlocked:false});
  await db.doc('settings/bookings').set({holdMinutes:30,qicard:{enabled:true,account:'test account'}});
  const venue=await call('saveBookingVenue','admin',{ownerId:'owner',name:'test venue',location:'Anbar',category:'farm',price:100000,deposit:25000,terms:'test terms',active:true});
  await assert.rejects(call('saveBookingVenue','owner',{ownerId:'owner'}));
  const data={venueId:venue.id,requestId:'request',start:Date.now()+86400000,end:Date.now()+90000000,acceptedTerms:'test terms',price:100000,deposit:25000};
  await assert.rejects(call('requestBooking','customer1',{...data,price:1}));
  const a=await call('requestBooking','customer1',data), b=await call('requestBooking','customer2',data);
  assert.equal((await call('requestBooking','customer1',data)).id,a.id);
  await assert.rejects(call('actOnBooking','stranger',{bookingId:a.id,action:'approve'}));
  const results=await Promise.allSettled([a,b].map(r=>call('actOnBooking','owner',{bookingId:r.id,action:'approve'})));
  assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
  const chosen=results[0].status==='fulfilled'?a:b, uid=chosen===a?'customer1':'customer2';
  const record=(await db.doc(`bookings/${chosen.id}`).get()).data();
  assert.equal(record.total,100000);assert.equal(record.customerName,uid);assert.equal(record.ownerName,'owner');assert.equal(record.venueName,'test venue');assert.equal(record.remaining,100000);
  await assert.rejects(call('actOnBooking','admin',{bookingId:chosen.id,action:'confirmPayment'}));
  const path=`booking_receipts/${chosen.id}/${uid}/123.jpg`;
  await getStorage().bucket().file(path).save(Buffer.from('test receipt'),{resumable:false,metadata:{contentType:'image/jpeg'}});
  await assert.rejects(call('actOnBooking','stranger',{bookingId:chosen.id,action:'submitPayment',receiptPath:path,method:'qicard',transactionNumber:'t1'}));
  await call('actOnBooking',uid,{bookingId:chosen.id,action:'submitPayment',receiptPath:path,method:'qicard',transactionNumber:'t1'});
  await assert.rejects(call('actOnBooking','owner',{bookingId:chosen.id,action:'confirmPayment'}));
  await call('actOnBooking','admin',{bookingId:chosen.id,action:'confirmPayment'});
  const paid=(await db.doc(`bookings/${chosen.id}`).get()).data();assert.equal(paid.paid,25000);assert.equal(paid.remaining,75000);
  await assert.rejects(call('actOnBooking',uid,{bookingId:chosen.id,action:'cancel',reason:'cancel'}));
  await assert.rejects(call('reportBooking','stranger',{bookingId:chosen.id,reason:'spam'}));
  await call('reportBooking',uid,{bookingId:chosen.id,reason:'report'});
  assert.equal((await db.doc(`booking_reports/${chosen.id}_${uid}`).get()).data().status,'open');
  const snap=await db.doc(`bookings/${chosen.id}`).get();
  const event={data:{after:snap,before:{data:()=>({status:'payment_review'})}},params:{bookingId:chosen.id}};
  await Promise.all([f.bookingNotifications.run(event),f.bookingNotifications.run(event)]);
  const notices=await db.collection('notifications').where('bookingId','==',chosen.id).get();assert.equal(notices.size,3);
  const next={...data,requestId:'adjacent',start:data.end,end:data.end+3600000};
  const adjacent=await call('requestBooking','customer1',next);
  await call('actOnBooking','owner',{bookingId:adjacent.id,action:'approve'});
  await db.doc(`bookings/${adjacent.id}`).update({holdUntil:Date.now()-1});
  const replacement=await call('requestBooking','customer2',{...next,requestId:'expired-replacement'});
  await call('actOnBooking','owner',{bookingId:replacement.id,action:'approve'});
  await f.expireBookingHolds.run({});
  assert.equal((await db.doc(`bookings/${adjacent.id}`).get()).data().status,'expired');
  assert.equal((await db.doc(`bookings/${replacement.id}`).get()).data().status,'held');
  await assert.rejects(call('actOnBooking','customer1',{bookingId:adjacent.id,action:'submitPayment',receiptPath:path,method:'qicard',transactionNumber:'late'}));
  await db.doc('users/customer2').update({isBlocked:true});
  await assert.rejects(call('requestBooking','customer2',{...next,requestId:'blocked'}));
});
