const {test}=require('node:test');
const assert=require('node:assert/strict');
const {initializeApp}=require('firebase-admin/app');
const {getFirestore}=require('firebase-admin/firestore');
if(process.env.GCLOUD_PROJECT!=='demo-aqar'||process.env.FIRESTORE_EMULATOR_HOST!=='127.0.0.1:8185')throw Error('Isolated emulator required');
initializeApp({projectId:'demo-aqar'});
const db=getFirestore(),f=require('./payment_accounts');
const call=(name,uid,data,claim=false)=>f[name].run({auth:{uid,token:{canManagePaymentAccounts:claim}},data});
const methods=(number='7066135323',enabled=true)=>({qicard:{number,enabled},zaincash:{number:'',enabled:false}});
test('server settings authorization, validation, audit, payment snapshot and disable lifecycle',async()=>{
 for(const uid of ['admin','owner','other','blocked']) await db.doc(`users/${uid}`).set({isAdmin:['admin','blocked'].includes(uid),isBlocked:uid==='blocked'});
 await db.doc(f.CONFIG).delete();
 await assert.rejects(call('savePaymentAccountSettings','admin',{revision:0,methods:methods()}));
 await assert.rejects(call('savePaymentAccountSettings','owner',{revision:0,methods:methods()},true));
 await assert.rejects(call('savePaymentAccountSettings','blocked',{revision:0,methods:methods()},true));
 await assert.rejects(call('savePaymentAccountSettings','admin',{revision:0,methods:methods('abc')},true));
 await call('savePaymentAccountSettings','admin',{revision:0,methods:methods()},true);
 assert.deepEqual((await db.doc('payment_accounts/shared').get()).data().methods,{qicard:{number:'7066135323',account:'7066135323',enabled:true}});
 await assert.rejects(call('savePaymentAccountSettings','admin',{revision:0,methods:methods()},true));
 await db.doc('offices/office').set({ownerId:'owner'});
 await db.doc('subscription_packages/pkg').set({name:'pkg',price:25000,currency:'IQD',isActive:true});
 const sub={officeId:'office',ownerId:'owner',packageId:'pkg',status:'pending',price:1};
 await db.doc('office_subscriptions/sub').set(sub);
 const payment={subscriptionId:'sub',paymentMethod:'qicard',expectedNumber:'7066135323',receiptUrl:'https://res.cloudinary.com/test/image/upload/receipt.jpg',transactionId:'tx',amount:1};
 await assert.rejects(call('createSubscriptionPayment','other',payment));
 await assert.rejects(call('createSubscriptionPayment','owner',{...payment,expectedNumber:'1111111111'}));
 const result=await call('createSubscriptionPayment','owner',payment);
 const original=(await db.doc(`subscription_payments/${result.id}`).get()).data();
 assert.equal(original.amount,25000);
 assert.deepEqual(original.paymentAccountSnapshot,{method:'qicard',number:'7066135323',revision:1});
 await call('savePaymentAccountSettings','admin',{revision:1,methods:methods('',false)},true);
 assert.deepEqual((await db.doc('payment_accounts/shared').get()).data().methods,{});
 await db.doc('office_subscriptions/sub2').set(sub);
 await assert.rejects(call('createSubscriptionPayment','owner',{...payment,subscriptionId:'sub2'}));
 assert.equal((await call('createSubscriptionPayment','owner',payment)).id,result.id);
 assert.deepEqual((await db.doc(`subscription_payments/${result.id}`).get()).data(),original);
 assert.equal((await db.collection('payment_account_audit').get()).size,2);
 assert.throws(()=>f.normalize({qicard:{number:'',enabled:true},zaincash:{number:'',enabled:false}}));
 assert.equal(f.validNumber('zaincash','07701234567'),true);
 assert.equal(f.validNumber('zaincash','7066135323'),false);
});
