const {test}=require('node:test');
const assert=require('node:assert/strict');
const {initializeApp}=require('firebase-admin/app');
const {getFirestore}=require('firebase-admin/firestore');
const {getStorage}=require('firebase-admin/storage');
if(process.env.GCLOUD_PROJECT!=='demo-aqar'||process.env.FIRESTORE_EMULATOR_HOST!=='127.0.0.1:8185')throw Error('Isolated emulator required');
initializeApp({projectId:'demo-aqar',storageBucket:'demo-aqar.appspot.com'});
const db=getFirestore(),f=require('./payment_accounts');
const call=(name,uid,data,claim=false)=>f[name].run({auth:{uid,token:{canManagePaymentAccounts:claim}},data});
const methods=(number='7066135323',enabled=true)=>({qicard:{number,enabled},zaincash:{number:'',enabled:false}});
test('server settings authorization, validation, audit, payment snapshot and disable lifecycle',async()=>{
 for(const uid of ['admin','owner','other','blocked']) await db.doc(`users/${uid}`).set({isAdmin:['admin','blocked'].includes(uid),isBlocked:uid==='blocked'});
 await db.doc(f.CONFIG).delete();
 await assert.rejects(call('savePaymentAccountSettings','admin',{revision:0,methods:methods()}));
 await assert.rejects(call('savePaymentAccountSettings','owner',{revision:0,methods:methods()},true));
 await assert.rejects(call('savePaymentAccountSettings','blocked',{revision:0,methods:methods()},true));
 await assert.rejects(call('savePaymentAccountSettings','admin',{revision:0,methods:methods('abc')},true));
 await call('savePaymentAccountSettings','admin',{revision:0,methods:methods()},true);
 assert.deepEqual((await db.doc('payment_accounts/shared').get()).data().methods,{qicard:{number:'7066135323',account:'7066135323',enabled:true}});
 await assert.rejects(call('savePaymentAccountSettings','admin',{revision:0,methods:methods()},true));
 await db.doc('offices/office').set({ownerId:'owner'});
 await db.doc('subscription_packages/pkg').set({name:'pkg',price:25000,currency:'IQD',isActive:true,durationDays:30,maxFeaturedProperties:7,featuredPropertiesEnabled:true});
 const sub={officeId:'office',ownerId:'owner',packageId:'pkg',status:'pending',price:1};
 await db.doc('office_subscriptions/sub').set(sub);
 const receiptPath='subscription_receipts/sub/owner/123.jpg';
 await getStorage().bucket().file(receiptPath).save(Buffer.from('receipt'),{resumable:false,metadata:{contentType:'image/jpeg'}});
 const payment={subscriptionId:'sub',paymentMethod:'qicard',expectedNumber:'7066135323',receiptPath,transactionId:'tx',amount:1};
 await assert.rejects(call('createSubscriptionPayment','other',payment));
 await assert.rejects(call('createSubscriptionPayment','owner',{...payment,expectedNumber:'1111111111'}));
 await assert.rejects(call('createSubscriptionPayment','owner',{...payment,receiptPath:'subscription_receipts/sub/other/123.jpg'}));
 await db.doc('subscription_packages/pkg').update({price:0.5});
 await assert.rejects(call('createSubscriptionPayment','owner',payment));
 await db.doc('subscription_packages/pkg').update({price:25000});
 const result=await call('createSubscriptionPayment','owner',payment);
 const original=(await db.doc(`subscription_payments/${result.id}`).get()).data();
 assert.equal((await db.doc('office_subscriptions/sub').get()).data().durationDays,30);
 assert.equal(original.amount,25000);
 assert.equal(original.receiptUrl,'');
 assert.equal(original.receiptPath,receiptPath);
 assert.deepEqual(original.paymentAccountSnapshot,{method:'qicard',number:'7066135323',revision:1});
 await db.doc('subscriptions/sub').set({...sub,ownerId:null,ownerUid:'owner'});
 const legacy = await call('createSubscriptionPayment','owner',{...payment,legacy:true});
 assert.notEqual(legacy.id,result.id);
 assert.equal((await db.doc(`subscription_payments/${legacy.id}`).get()).data().subscriptionCollection,'subscriptions');
 await call('savePaymentAccountSettings','admin',{revision:1,methods:methods('',false)},true);
 assert.deepEqual((await db.doc('payment_accounts/shared').get()).data().methods,{});
 await db.doc('office_subscriptions/sub2').set(sub);
 await assert.rejects(call('createSubscriptionPayment','owner',{...payment,subscriptionId:'sub2'}));
 assert.equal((await call('createSubscriptionPayment','owner',payment)).id,result.id);
 assert.deepEqual((await db.doc(`subscription_payments/${result.id}`).get()).data(),original);
 const event={id:'payment-create-test',params:{paymentId:result.id},data:{before:{data:()=>undefined},after:{data:()=>original}}};
 await Promise.all([f.auditSubscriptionPayment.run(event),f.auditSubscriptionPayment.run(event)]);
 assert.equal((await db.collection('subscription_payment_audit').where('paymentId','==',result.id).get()).size,1);
 assert.equal((await db.collection('payment_account_audit').get()).size,2);
 const approvals=await Promise.allSettled([1,2].map(()=>call('reviewOfficeSubscription','admin',{subscriptionId:'sub',action:'approve'})));
 assert.equal(approvals.filter(r=>r.status==='fulfilled').length,1);
 assert.equal((await db.doc('offices/office').get()).data().subscriptionStatus,'active');
 assert.equal((await db.doc('office_subscriptions/sub').get()).data().maxFeaturedProperties,7);
 await assert.rejects(call('reviewOfficeSubscription','admin',{subscriptionId:'sub',action:'reject'}));
 assert.equal((await db.collection('subscription_review_audit').get()).size,1);
 await db.doc('office_subscriptions/sub').update({featuredPropertiesUsed:3});
 const firstEnd=(await db.doc('office_subscriptions/sub').get()).data().endDate.toMillis();
 await db.doc('office_subscriptions/old_pending').set({...sub,price:25000,currency:'IQD',durationDays:9999,maxProperties:0,maxFeaturedProperties:7,canFeatureProperties:true,canAppearInFeaturedOffices:false,canUseAdvancedStatistics:true});
 const historical={officeId:'office',ownerUid:'owner',subscriptionId:'old_pending',packageId:'pkg',amount:25000,status:'pending',receiptUrl:'https://res.cloudinary.com/old/image/upload/historical.jpg',paymentAccount:'old account'};
 await db.doc('subscription_payments/old_pending').set(historical);
 await db.doc('users/owner').update({isAdmin:true});
 await assert.rejects(call('reviewOfficeSubscription','owner',{subscriptionId:'old_pending',action:'approve'}));
 await assert.rejects(call('reviewOfficeSubscription','admin',{subscriptionId:'old_pending',action:'approve'}));
 // Emulator-only approved contract correction; never mutate historical production terms automatically.
 await db.doc('office_subscriptions/old_pending').update({durationDays:30});
 await call('reviewOfficeSubscription','admin',{subscriptionId:'old_pending',action:'approve'});
 const renewed=(await db.doc('office_subscriptions/old_pending').get()).data();
 assert.equal(renewed.durationDays,30);
 assert.equal(renewed.maxFeaturedProperties,11);
 assert.equal(renewed.endDate.toMillis(),firstEnd+30*86400000);
 assert.equal((await db.doc('office_subscriptions/sub').get()).data().status,'expired');
 const historicalAfter=(await db.doc('subscription_payments/old_pending').get()).data();
 assert.equal(historicalAfter.receiptUrl,historical.receiptUrl);
 assert.equal(historicalAfter.paymentAccount,historical.paymentAccount);
 assert.equal(historicalAfter.paymentAccountSnapshot,undefined);
 await db.doc('office_subscriptions/rejected_renewal').set(sub);
 await db.doc('subscription_payments/rejected_renewal').set({...historical,subscriptionId:'rejected_renewal'});
 await call('reviewOfficeSubscription','admin',{subscriptionId:'rejected_renewal',action:'reject'});
 assert.equal((await db.doc('offices/office').get()).data().subscriptionId,'old_pending');
 assert.equal((await db.doc('offices/office').get()).data().subscriptionStatus,'active');
 assert.throws(()=>f.normalize({qicard:{number:'',enabled:true},zaincash:{number:'',enabled:false}}));
 assert.equal(f.validNumber('zaincash','07701234567'),true);
 assert.equal(f.validNumber('zaincash','7066135323'),false);
});
